[project]
name = "paio"
version = "1.0.0"
description = "Paio 是一个基于 Python 的音乐播放器，它集成了音乐下载、播放、歌词显示、播放列表管理等功能。"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.13",
    "pywebview>=5.4",
    "uvicorn>=0.34.3",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true
